### ISSUE TITLE
Application not working, any help would be awesome

### ISSUE THREAD

**Issue by CallumCarmicheal** [bp2008/HdmiExtender#2]
I recently needed a capture card for development (high fps is not a requirement just a visual like 15 fps is fine), I came across the blog posts about the V2 so i picked it up because i work on windows i downloaded and compiled this source and could not get visual.

I have opened wire shark and i am receiving information from the device like this for example, the IP is the same as the one in the source so I don't need to change it.
![capture](https://user-images.githubusercontent.com/6545688/39209968-43208446-47ff-11e8-8935-7657a40e2bb3.PNG)

Although all my efforts i cannot get it to display the screen or audio to work, any help would be greatly appreciated. I know this is a old project and you prob have not thought about it in literally a few years just have to chance my luck ^.^

**Comment by Synergyst** [comment]
I can confirm I am getting the same issue here..

**Comment by danielkucera** [comment]
guys, which version of tx do you have?

**Comment by danielkucera** [comment]
can you try to change +3 to -311 on this line?
https://github.com/bp2008/HdmiExtender/blob/60f3972d577936ab532a116be4919d538d92c6c6/HdmiExtender/HdmiExtenderLib/HdmiExtenderReceiver.cs#L187

**Comment by markosc** [comment]
V2.0 extender tx sender

**Comment by danielkucera** [comment]
https://github.com/danielkucera/golkv373

**Comment by markosc** [comment]
> https://github.com/danielkucera/golkv373
Interestingly, it is necessary to have the "receiver" and that only the one that "sends" it will be defective and will not find the mjpeg

**Comment by kurokobo** [comment]
It seems this issue hasn't been updated for a long time, but I'm writing some tips for someone in trouble in the future.

I had exactly the same issue in my environment.
And in my situation, the root cause was the Windows Defender Firewall.
I changed the settings of Windows Firewall finally I could see visuals in my browser.

The `HdmiExtenderService` had been blocked by default in Public profile in Inbound Rules. I had to make this allowed in order for me to get images because my NIC which connected to "Sender" uses the Public profile.

This is my environment:
* Windows 10 Pro 1903
* Visual Studio Community 2019
* WinPcap 4.1.3
    * WinPcap is not supported in Windows 10, but the `Pcap.Net` in `HdmiExtender` doesn't work with current Npcap... :(

And my solution is:
* Build this project in Release mode.
* Invoke `.\HdmiExtenderService.exe` with argument `cmd` like `.\HdmiExtenderService.exe cmd`.
* Allow `HdmiExtenderService` in Public profile in the Windows Defender Firewall.
* Open `http://localhost:18080/raw.html`.

UPDATE:
F.Y.I., danielkucera's https://github.com/danielkucera/golkv373 works for me correctly on my WIndows PC without "Receiver" too.
The only thing I have to do is to allow `golkv373-v0.5.1-win32.exe` in the specific profile which the NIC uses in the Windows Defender Firewall the same as commented above.
We can investigate which profile used per NIC by `Get-NetConnectionProfile` commandlet.
Thank you for great work :)
